# Generated by Django 4.1 on 2024-06-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicacao',
            new_name='publicada',
        ),
    ]
